### ISSUE TITLE
How do I install this in chromium ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [xntrik/aws-saml-capture-extension#1]
Do I need to somehow compile the extension locally, or ?

**Comment by xntrik** [comment]
If you download the repo into a folder, and then go to your Chrome Extensions page you can change it to "Developer Mode". From there you should now see a button called "Load Unpacked" from that button you can select the folder where you downloaded this repo and it should install. 

It's not super graceful :/ (and I hacked this together to solve a very specific problem I was facing)

**Comment by xntrik** [comment]
<img width="1487" alt="Screen Shot 2021-02-12 at 10 19 39 am" src="https://user-images.githubusercontent.com/678260/107723405-04161500-6d1c-11eb-8c5d-8e9dbb7711f4.png">
